[package]
name = "aozora-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
aozora-rs-core = { workspace = true }
aozora-rs-epub = { workspace = true }
aozora-rs-xhtml = { workspace = true }
winnow.workspace = true
