[package]
name = "aozora-rs-xhtml"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aozora-rs-core = { path = "../aozora-rs-core" }
itertools = "0.14.0"
miette = { version = "7.6", features = ["fancy"] }
winnow = "0.7.14"
