[package]
name = "aozora-rs-xhtml"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aozora-rs = { path = "../aozora-rs" }
miette = { version = "7.6", features = ["fancy"] }
wasm-bindgen = "0.2"
winnow = "0.7.14"

[features]
debug = []
