[package]
name = "aozora-rs-core"
version = "0.1.0"
edition = "2024"

[dependencies]
aozora-rs-gaiji = { path="../aozora-rs-gaiji" }
encoding_rs = "0.8.35"
enum_dispatch = "0.3.13"
miette = "7.6.0"
thiserror = "2.0.17"
winnow = "0.7.14"
