[package]
name = "ayame-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ayame"
path = "src/main.rs"

[dependencies]
ayame-core = { workspace = true }
aozora-rs = { workspace = true }
clap = { workspace = true }
miette = { workspace = true }
